version: "2"
services:
  web:
    image: "php:7.0-apache"
    container_name: "webserver"
    links:
      - "mysql"
    depends_on:
      - "mysql"
    ports:
      - "80:80"
  mysql:
    image: "mysql:5.7.16"
    container_name: "mysql"
    ports:
      - "3306:3306"
