version: "2"
services:
  silex:
    image: "php:7.0-apache"
    container_name: "silex"
    links:
      - "mysql"
    depends_on:
      - "mysql"
    ports:
      - "80:80"
    volumes:
      - "./app:/var/www/html/"
